# Source: https://leetcode.com/problems/find-the-difference/description/
# Author: Paulo Lemus
# Date  : 2017-11-09
# Number: 389

# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.

class Solution:
    def findTheDifference(self, s, t):
	"""
	:type s: str
	:type t: str
	:rtype: str
	"""
	outlier = 0

	for letter in s:
	    outlier ^= ord(letter)
	for letter in t:
	    outlier ^= ord(letter)
	return chr(outlier)

